services:
  postgres:
    image: postgres:16.4-alpine
    container_name: next_saas_starter_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000" 
  #   depends_on:
  #     - backend
  #   volumes:
  #     - .:/app
  #     - /app/node_modules/
  #     - /app/.next/
  backend:
    build:
      context: .
      dockerfile: ./app/api/ai-apis/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./stable-diffusion:/app/stable-diffusion
  comfyui-internal:
    build:
      context: ./stable-diffusion/ComfyUI
      dockerfile: Dockerfile
    ports:
      - "8188:8188"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  postgres_data:
